TrainingDataFile = r'../resources/199801_seg&pos.txt'
SolveFile = r'../resources/199801_sent.txt'
DictFile = r'../results/dict.txt'
seg_FMM = r'../results/seg_FMM.txt'
seg_BMM = r'../results/seg_BMM.txt'
