TrainingDataFile = r'../resources/199801_seg&pos.txt'
SolveFile = r'../resources/199801_sent.txt'
Unigram_Dict = r'../results/unigram_dict.txt'
seg_Unigram = r'../results/seg_Unigram.txt'
Bigram_Dict = r'../results/bigram_dict.txt'
seg_Bigram = r'../results/seg_Bigram.txt'
